spring:
  application:
    name: evaluador-service
server:
  port: ${PORT:8081}
eureka:
  instance:
    status-page-url-path: /evaluar?expresion=2+2
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
