server:
  port: ${PORT:9090}

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: false
#zuul:
#  routes:
#    evaluador:
#      path: /calculadora/**
#      url: http://localhost:8081

zuul:
  routes:
    EVALUADOR-SERVICE:
      path: /calculadora/**

