server:
  port: ${PORT:9090}


eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
    registerWithEureka: true

zuul:
  routes:
    EVALUADOR-SERVICE:
      path: /**
spring:
  application:
    name: gateway
