spring:
  application:
    name: client-service
cloud:
  config:
    server:
      git:
        uri: https://github.com/piomin/sample-spring-cloud-config-repo.git
        username: ${github.username}
        password: ${github.password}
        cloneOnStart: true